#dependabot config form NPM

version: 2
updates:
  - directory: "/"
    package-ecosystem: npm
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
      day: "wednesday"
    groups:
      eslint:
        patterns:
          - "eslint*"
          - "@typescript-eslint*"
